### ISSUE TITLE
[win32 instantdex] Wrong NXT API call

### ISSUE THREAD

**Issue by blackyblack** [jl777/libjl777#16] opened 2015-08-18 16:47 UTC
BitcoinDarkd crashed after placebid call:

_cmd.(requestType=getCurrency&currency=3977863981551859762)
(3977863981551859762) not asset and not currency ({"errorDescription":"Unknown currency","errorCode":5})

It is mgwLTC asset but NXT call for a currency.

**Comment by jl777** [comment] 2015-08-18 17:02
it seems not the latest source that knows about LTC asset id, but the above shouldnt be the cause of crash. seems win32 specific issue, hopefully we can find out where it is crashing

**Comment by blackyblack** [comment] 2015-08-18 17:13
I agree. In another call getCurrency failed but BitcoinDarkd did not crash.

**Comment by jl777** [comment] 2015-08-18 18:34
old version did not succeed in windows to make placebid network call, I think this is the reason for this, so I will close this

**Closed by jl777** 2015-08-18 18:34 UTC
